services:
  test-drive:
#    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: test-drive  # tag can be added.
#    platform: linux/arm64
    volumes:
      - .:/home/gradle/self-hosted-runner-test-drive
