name: Self Hosted Runner Test Drive
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  github-hosted:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Greeting
        run: echo "Hello World from Github!"

  self-hosted:
    runs-on: self-hosted
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
      - name: Greeting
        run: echo "Hello World from Self-Hosted Runner!"
              