name: Self Hosted Runner Test Drive
on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  github-hosted:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
      - name: Java version
        run: java -v
      - name: Gradle version
        run: gradle -v
      - name: Get code
        uses: actions/checkout@v4
      - name: Greeting
        run: echo "Hello World from Github!"

  self-hosted:
    runs-on: self-hosted
#    defaults:
#      run:
#        working-directory: /tmp
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
      - name: Greeting
        run: |
          hostname
          echo "Hello World from Self-Hosted Runner!"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
              